/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prop;

import Config.Session;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import kepegawaian.Selecteventmenu;
import model.model_menu;

/**
 *
 * @author Axel
 */
public class Menu extends javax.swing.JPanel {
String lev = Session.getLevel();
String nama = Session.getNama();
     private Selecteventmenu event;
     
     public void addevent(Selecteventmenu event){
     this.event=event;
     listmenu1.addevent(event);
     };
     
    public Menu() {
        initComponents();
       listmenu1.setOpaque(false);
//       listmenu1.setBackground(new Color(0,0,0,55));
        setOpaque(false);
        init();
      nam.setText("Nama: "+nama+". Level: "+lev+" ");
    }
  
private void init(){
    listmenu1.additem(new model_menu("pegawai","Pegawai",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("user","User",model_menu.menutype.MENU));
 listmenu1.additem(new model_menu("absen","Absensi",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("pekerjaan","Detail Kerja",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("fprint","Finger print",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("presensi","Presensi",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("pendidikan","Pendidikan",model_menu.menutype.MENU));

 listmenu1.additem(new model_menu("","Data Master",model_menu.menutype.EMPTY));

listmenu1.additem(new model_menu("divisi","Divisi",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("kantor","Kantor",model_menu.menutype.MENU));

 listmenu1.additem(new model_menu("","Menu",model_menu.menutype.EMPTY));
listmenu1.additem(new model_menu("Logout","Logout",model_menu.menutype.MENU));
listmenu1.additem(new model_menu("Close","Exit",model_menu.menutype.MENU));



}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nam = new javax.swing.JLabel();
        listmenu1 = new prop.listmenu<>();

        movepanel.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_staff_80px_1.png"))); // NOI18N
        jLabel1.setText("SIMPEG");

        nam.setFont(new java.awt.Font("Geometr706 BlkCn BT", 0, 14)); // NOI18N
        nam.setForeground(new java.awt.Color(255, 255, 255));
        nam.setText("-");

        javax.swing.GroupLayout movepanelLayout = new javax.swing.GroupLayout(movepanel);
        movepanel.setLayout(movepanelLayout);
        movepanelLayout.setHorizontalGroup(
            movepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movepanelLayout.createSequentialGroup()
                .addGroup(movepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, movepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        movepanelLayout.setVerticalGroup(
            movepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listmenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(movepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
GradientPaint g= new GradientPaint(0, 0, Color.decode("#0052D4"), 0, getHeight(), Color.decode("#9CECFB"));
g2.setPaint(g);
g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
super.paintChildren(grphcs);
       //To change body of generated methods, choose Tools | Templates.
    }
    
    private int x;
    private int y;
    
public void initMoving(JFrame fram){
movepanel.addMouseListener(new MouseAdapter(){
    @Override
    public void mousePressed(MouseEvent e) {
x = e.getX();
y = e.getY();
    }
});

movepanel.addMouseMotionListener(new MouseMotionAdapter(){
    @Override
    public void mouseDragged(MouseEvent e) {
      fram.setLocation(e.getXOnScreen()-x, e.getYOnScreen()-y);
    }

});

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private prop.listmenu<String> listmenu1;
    private javax.swing.JPanel movepanel;
    private javax.swing.JLabel nam;
    // End of variables declaration//GEN-END:variables
}
