/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prop;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import model.model_menu;

/**
 *
 * @author Axel
 */
public class menuitem extends javax.swing.JPanel {

    /**
     * @param selected the selected to set
     */
  

  private boolean selected;
  private boolean over;
    public menuitem(model_menu data) {
        initComponents();
        setOpaque(false);
        if (data.getType()==model_menu.menutype.MENU) {
            lbicon.setIcon(data.toicon());
            lbname.setText(data.getName());
        }else if (data.getType()==model_menu.menutype.EMPTY) {
            lbname.setText(data.getName());
            lbicon.setFont(new Font("sansserif", 1, 12));
        }else{
        lbname.setText("");
        }
    }

      public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
      public void setover(boolean over){
      this.over= over;
      repaint();
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        lbicon = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(0, 0, 255));

        lbname.setBackground(new java.awt.Color(255, 255, 255));
        lbname.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        lbname.setForeground(new java.awt.Color(51, 51, 51));
        lbname.setText("menu name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbicon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbname)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbicon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        if (selected  || over) {
               Graphics2D g2 = (Graphics2D) grphcs;
g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            if (selected) {
                g2.setColor(new Color(255,255,255,80));
            }else {
            g2.setColor(new Color(255,255,255,20));
            }
g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        }
        super.paintComponent(grphcs); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbicon;
    private javax.swing.JLabel lbname;
    // End of variables declaration//GEN-END:variables
}
